"""baseline

Revision ID: 0001
Revises: 
Create Date: 2026-07-07 13:21:41.861473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('deny_reason', sa.Text(), nullable=True),
    sa.Column('temp_password', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('account_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_requests_token'), ['token'], unique=True)

    op.create_table('app_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('indexer_torrents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('info_hash', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('indexer', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('seeders', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(length=16), nullable=False),
    sa.Column('magnet_url', sa.Text(), nullable=True),
    sa.Column('download_url', sa.Text(), nullable=True),
    sa.Column('guid', sa.String(length=512), nullable=True),
    sa.Column('parsed_isbn', sa.String(length=20), nullable=True),
    sa.Column('title_norm', sa.String(length=512), nullable=False),
    sa.Column('author_norm', sa.String(length=256), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_indexer_fetch_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rd_cached', sa.Boolean(), nullable=False),
    sa.Column('torbox_cached', sa.Boolean(), nullable=False),
    sa.Column('last_debrid_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('indexer_torrents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_indexer_torrents_info_hash'), ['info_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_indexer_torrents_parsed_isbn'), ['parsed_isbn'], unique=False)
        batch_op.create_index(batch_op.f('ix_indexer_torrents_title_norm'), ['title_norm'], unique=False)

    op.create_table('library_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('invite_code', sa.String(length=24), nullable=False),
    sa.Column('real_debrid_api_token', sa.Text(), nullable=False),
    sa.Column('torbox_api_token', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('library_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_library_groups_invite_code'), ['invite_code'], unique=True)

    op.create_table('scraper_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('last_query_index', sa.Integer(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('torrents_total', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_debrid_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_query', sa.String(length=256), nullable=True),
    sa.Column('last_upserted_count', sa.Integer(), nullable=False),
    sa.Column('last_matches_created', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('private_mode', sa.Boolean(), nullable=False),
    sa.Column('preferred_debrid', sa.String(length=16), nullable=False),
    sa.Column('library_group_id', sa.Integer(), nullable=True),
    sa.Column('library_role', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['library_group_id'], ['library_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('abs_play_tracking',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('abs_item_id', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('author', sa.String(length=256), nullable=False),
    sa.Column('hidden', sa.Boolean(), nullable=False),
    sa.Column('last_played_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('abs_play_tracking', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_abs_play_tracking_abs_item_id'), ['abs_item_id'], unique=False)

    op.create_table('catalog_torrent_matches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('google_volume_id', sa.String(length=64), nullable=False),
    sa.Column('info_hash', sa.String(length=64), nullable=False),
    sa.Column('match_method', sa.String(length=16), nullable=False),
    sa.Column('match_tier', sa.String(length=16), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['info_hash'], ['indexer_torrents.info_hash'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('catalog_torrent_matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_catalog_torrent_matches_google_volume_id'), ['google_volume_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_catalog_torrent_matches_info_hash'), ['info_hash'], unique=False)

    op.create_table('download_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('author', sa.String(length=256), nullable=True),
    sa.Column('magnet_link', sa.Text(), nullable=False),
    sa.Column('indexer', sa.String(length=128), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('media_type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('status_detail', sa.Text(), nullable=True),
    sa.Column('rd_torrent_id', sa.String(length=64), nullable=True),
    sa.Column('aa_file_extension', sa.String(length=16), nullable=True),
    sa.Column('progress_percent', sa.Float(), nullable=True),
    sa.Column('progress_bytes', sa.Integer(), nullable=True),
    sa.Column('progress_total_bytes', sa.Integer(), nullable=True),
    sa.Column('progress_speed_bps', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('push_subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(length=1024), nullable=False),
    sa.Column('p256dh', sa.String(length=256), nullable=False),
    sa.Column('auth', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stream_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('author', sa.String(length=256), nullable=False),
    sa.Column('cover_url', sa.String(length=1024), nullable=False),
    sa.Column('magnet_link', sa.Text(), nullable=True),
    sa.Column('download_url', sa.Text(), nullable=True),
    sa.Column('indexer', sa.String(length=128), nullable=True),
    sa.Column('rd_torrent_id', sa.String(length=64), nullable=True),
    sa.Column('debrid_provider', sa.String(length=16), nullable=False),
    sa.Column('tracks_json', sa.Text(), nullable=True),
    sa.Column('progress_seconds', sa.Float(), nullable=False),
    sa.Column('total_seconds', sa.Float(), nullable=False),
    sa.Column('current_track_index', sa.Integer(), nullable=False),
    sa.Column('track_position_seconds', sa.Float(), nullable=False),
    sa.Column('hidden', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('streaming_library',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('google_volume_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('author', sa.String(length=256), nullable=False),
    sa.Column('cover_url', sa.String(length=1024), nullable=False),
    sa.Column('genre', sa.String(length=128), nullable=False),
    sa.Column('magnet_link', sa.Text(), nullable=True),
    sa.Column('rd_torrent_id', sa.String(length=64), nullable=True),
    sa.Column('debrid_provider', sa.String(length=16), nullable=False),
    sa.Column('stream_status', sa.String(length=32), nullable=False),
    sa.Column('progress_seconds', sa.Float(), nullable=False),
    sa.Column('total_seconds', sa.Float(), nullable=False),
    sa.Column('tracks_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('streaming_library')
    op.drop_table('stream_history')
    op.drop_table('search_history')
    op.drop_table('push_subscriptions')
    op.drop_table('download_requests')
    with op.batch_alter_table('catalog_torrent_matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_catalog_torrent_matches_info_hash'))
        batch_op.drop_index(batch_op.f('ix_catalog_torrent_matches_google_volume_id'))

    op.drop_table('catalog_torrent_matches')
    with op.batch_alter_table('abs_play_tracking', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_abs_play_tracking_abs_item_id'))

    op.drop_table('abs_play_tracking')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    op.drop_table('scraper_state')
    with op.batch_alter_table('library_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_library_groups_invite_code'))

    op.drop_table('library_groups')
    with op.batch_alter_table('indexer_torrents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_indexer_torrents_title_norm'))
        batch_op.drop_index(batch_op.f('ix_indexer_torrents_parsed_isbn'))
        batch_op.drop_index(batch_op.f('ix_indexer_torrents_info_hash'))

    op.drop_table('indexer_torrents')
    op.drop_table('app_settings')
    with op.batch_alter_table('account_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_requests_token'))

    op.drop_table('account_requests')
    # ### end Alembic commands ###
